name: Notify Build-zvmsdk for Packaging

on:
  push:
    branches:
      - main

jobs:
  notify_buildsdk:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Build-zvmsdk Packaging
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"event_type": "feilong_update", "client_payload": {"ref": "${{ github.ref }}"}}' \
          https://api.github.com/repos/aazam-gh/build-zvmsdk/dispatches \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
